### ISSUE TITLE
Site does not display after refresh in Chrome

### ISSUE THREAD

**Issue by markwhitfeld** [mscraftsman/devcon2019#93]
The site fails to load in Chrome after refreshing.
If I then do a hard refresh then it works again, but upon hitting F5 it goes blank again.

The error in the console is:
![image](https://user-images.githubusercontent.com/1948265/55333450-ad8cee00-5497-11e9-82b5-bd5085d2edcc.png)

**Comment by MrSunshyne** [comment]
I'm not able to reproduce this issue. 

Chrome  73 macOS

**Comment by markwhitfeld** [comment]
That's strange.
Seems to be an issue with the way that the service worker is serving up the css file.
If I bypass the service worker in the dev tools then it fixes the problem.

I am using Chrome 73 on Windows

**Comment by MrSunshyne** [comment]
Hi @markwhitfeld, I managed to replicate the issue. This error is shown when the css files do not exist. Since we're deploying new builds every few hours or so. Your browser might have cached the html page and is trying to request an expired css file. A simple CTRL + F5 fixed it for me. Not all users will be able to do that though. 

Your comment about the service-worker seems add up to the above.

**Comment by markwhitfeld** [comment]
I previously reproduced the issue by pressing CTRL + F5 which would load a fresh version of the full site and the when I pressed F5 and it would have the issue.

It seems like the issue is fixed now though. Confirmed working on my pc and phone.
Would love to know what fixed it.

**Comment by MrSunshyne** [comment]
Sorry to disappoint :P 
I don't think it's resolved yet. Must be just luck for now
